### ISSUE TITLE
Cell not editable when forceFitColumns=False

### ISSUE THREAD

**Issue by louismartin** [quantopian/qgrid#105]
Hello,
I just installed qgrid and I think I found an issue.
When I want to edit a cell by double clicking it works fine when using the following:
```
qgrid.show_grid(df)
```

But as soon as I set the option forceFitColumns to False, the cells become non-editable.
```
qgrid.set_defaults(grid_options={'forceFitColumns': False})
qgrid.show_grid(df)
```

qgrid==0.3.2
jupyter==1.0.0
jupyter-client==4.4.0
python 3.5.2

**Comment by TimShawver** [comment]
This should be fixed in the new beta for qgrid 1.0.  Could you follow the installation instructions in the [updated readme page](https://github.com/quantopian/qgrid#installation) and let me know if you still see the same issue? Thanks.
