### ISSUE TITLE
Not working on dashboards

### ISSUE THREAD

**Issue by jluttine** [quantopian/qgrid#108]
Qgrid isn't working on Jupyter Dashboard. I get the following error:
```
GET /dashboards/status-sites/nbextensions/qgridjs/qgrid.widget.js 404 22.122 ms - 1002
```
where `status-sites` is the name of the notebook.

Qgrid is working perfectly when running notebooks on my Jupyter notebook server. My dashboard is working perfectly with ipywidgets, except that qgrid doesn't work. The dashboard, kernel gateway and notebook server are all run in the same conda environment. Any ideas what could be wrong?

I opened this issue also in the dashboard project: https://github.com/jupyter-incubator/dashboards_server/issues/316

**Comment by TimShawver** [comment]
I'm hoping the fix I have in mind for https://github.com/quantopian/qgrid/issues/85 will also fix this.  I'll be sure to update this issue once I finish that fix.

**Comment by TimShawver** [comment]
It seems like development on the dashboard project is not continuing and the Jupyter team's plan is to instead add dashboarding functionality to Jupyterlab instead. See https://github.com/jupyterlab/jupyterlab/issues/1640 for more context. For that reason I'm closing this with a "won't fix" label.
