### ISSUE TITLE
Nothing displayed on notebook 5.0.0

### ISSUE THREAD

**Issue by tebeka** [quantopian/qgrid#109]
If you run the demo notebook under jupyter notebook 5.0.0 the qgrid grids are not displayed.

**Comment by KEBO80** [comment]
I have the same issue. The toolbar still is shown, but not the grid. I get the following 404 GET error

 404 GET /nbextensions/widgets/widgets/js/widget.js?v=20170421090618

**Comment by ngedev** [comment]
It works after simply replacing the ipython version in the first line of qgrid.widget.js
`if (IPython.version[0] === '4' && parseInt(IPython.version[2]) >= 2)`
-->
`if (IPython.version[0] === '4' && parseInt(IPython.version[2]) >= 2 || IPython.version[0] === '5')`

**Comment by KEBO80** [comment]
@ngedev : Great!! It works.

**Comment by leoalekseyev** [comment]
Took me a while to find this bug, but I just submitted a PR #112

**Comment by TimShawver** [comment]
Closing, as this is now fixed in the latest release, v0.3.3. Thanks for reporting this and figuring out the fix.
