### ISSUE TITLE
DataFrames with DatetimeIndex have dates rendered off by a day.

### ISSUE THREAD

**Issue by ssanderson** [quantopian/qgrid#11]
![screen shot 2014-10-13 at 7 17 06 pm](https://cloud.githubusercontent.com/assets/1588357/4621677/2d0f426e-532f-11e4-8942-20f2d7f5ab0f.png)

**Comment by epifanio** [comment]
Hi, I was also looking into rendering dataframe with timestamp (mine has microseconds as precision). Is there a way to increase the time resolution for the qgrid dataframe filter tool?

**Comment by TimShawver** [comment]
@epifanio there's no way to do that, sorry.  I don't expect we'll add support for microseconds anytime soon because it's a pain to handle in Javascript.

**Comment by TimShawver** [comment]
Fixed a while ago.
