### ISSUE TITLE
Two qgrid tables

### ISSUE THREAD

**Issue by iamjeet** [quantopian/qgrid#111]
I am currently using the master version and every time I run qgrid.show_grid(df) I get two qgrid tables. Is anyone else seeing this issue?

![screen shot 2017-04-25 at 3 00 24 pm](https://cloud.githubusercontent.com/assets/10838503/25409743/11ef5ce0-29c8-11e7-9c31-b4b4e7c00b08.png)

**Comment by t0mk** [comment]
same here. I installed from gihtub master 44f8d60

**Comment by nurogabe** [comment]
There is a display call in show_grid, easiest fix is to assign the call to a variable such as _, this will avoid displaying both tables.

**Comment by t0mk** [comment]
thanks. This works for me
```
_ = qgrid.show_grid(...)
```

**Comment by TimShawver** [comment]
Closing, because I just merged a fix for this and included it in the latest release.  Thanks for reporting and feel free to let me know if you guys are still seeing this issue after updating to v0.3.3, which is now available on PyPI.
