### ISSUE TITLE
Grid not showing in Jupyter notebook

### ISSUE THREAD

**Issue by FDara** [quantopian/qgrid#115]
Is there any reason grid does not show up on my Jupyter notebook?

I feel this is a common problem that some people had but i dont understand solutions which were provided. Please help

import pandas as pd
import qgrid
import numpy as np
qgrid.nbinstall(overwrite=True)  
qgrid.set_defaults(remote_js=True, show_toolbar=True)
from IPython.display import display
df3 = pd.DataFrame(np.random.randint(0,100,size=(100, 4)), columns=list('ABCD'))
grid = qgrid.QGridWidget(df=df3)
display(grid)

**Comment by cchuang2009** [comment]
Followed the qgrid for a while, It's really awesome. However, it is also inevitable to conflict with the ipywidget. After try and error, it works now for me.  Here my environment:

IPython 6.1.0
ipywidgets 6.0.0
qgrird 0.3.3

Anaconda Python3.6 on Mac system

After installation, modify $anaconda/etc/jupyter/nbconfig/notebook.json as follows:

{
  "load_extensions": {
   ...
    "qgrid/qgridjs/qgrid.widget": true
  }
}


and make share qgrid had been copy to $Anaconda/share/jupyter/nbextensions as named qgrid (not qgridjs).

 Restart jupyter notebook, qgrid should be come back again. 

ps, a demo of mime,

import qgrid
import pandas as pd
qgrid.nbinstall(overwrite=True) 

df = pd.DataFrame.from_csv('data/test.csv',index_col=0,parse_dates=[0],encoding="utf-8")
qgrid.show_grid(df,show_toolbar=True, grid_options={'forceFitColumns': False, 'defaultColumnWidth': 200})

# or

from IPython.display import display
grid = qgrid.QGridWidget(df=df)
display(grid)


Hope this do help to you

cch

**Comment by TimShawver** [comment]
In case anyone is still seeing this issue, please try installing the new qgrid 1.0 beta using the instructions here: https://github.com/quantopian/qgrid#installation. Only caveat for using qgrid 1.0 is that you need to be using ipywidgets version 7.x or newer.

I'm going to close this for now...please open a new issue if you still see this issue on qgrid 1.0.

**Comment by stef30360** [comment]
Hello, 
I have the same problem with the last version of Qgrid 1.0, ipywidget 7.

**Comment by TimShawver** [comment]
OK, have you tried creating a new virtual env or conda env, and then reinstalling qgrid? If that doesn't work, can you copy the following to your reply and fill in the blanks:

#### Environment Details:
* Operating System: (Mac OS Sierra, Windows 10, Linux, etc)
* Browser: (Chrome, Firefox, IE, etc)
* Python Version: (get this via `$ python --version`)
* How did you install Qgrid: (`pip`, `conda`, or `other (please explain)`)
* Notebook version:  (get this via`$ pip freeze`)
* ipywidgets version: (get this via`$ pip freeze`)
* qgrid version: (get this via`$ pip freeze`)

#### Other Details:
* Do you see any errors in the notebook server logs or the js console in the dev tools for your browser?
* Is anything printed in the notebook when the cell is executed?

Thanks.

**Comment by stef30360** [comment]
Hi, Thanks for your quick answer.

 **Environment Details:**
- Operating System: Mac OS High Sierra
- Browser: Chrome
- Python Version: 3.6.4

-How did you install Qgrid: I have the last anaconda distribution. I installed with `conda install -c tim_shawver/label/dev qgrid==1.0.0b10` .  My ipywydget work normaly , but not Qgrid ?

-Notebook version: 5.2.2
-ipywidgets version: 7.0.5
-qgrid version: 1.0.0.b10


**Others details**
<img width="762" alt="capture d ecran 2017-12-31 a 11 07 10" src="https://user-images.githubusercontent.com/11021144/34460838-eb36a078-ee1a-11e7-9ed9-7a20e5a5be02.png">

other way....
<img width="737" alt="capture d ecran 2017-12-31 a 11 10 23" src="https://user-images.githubusercontent.com/11021144/34460849-43d6cb40-ee1b-11e7-809d-7d0d34ca51d5.png">

Thanks you for your answer.
Regards,
SR

**Comment by TimShawver** [comment]
OK thanks. Your first attempt is correct, `nbinstall` no longer exists in qgrid 1.0.  

Regarding the error message in the first attempt: I've seen that error message before, and for me it happens if I execute a cell to create a qgrid widget, I save the notebook with the qgrid widget, I restart the kernel, and then reload notebook in my browser. Is it possible that's what's happening here, and you just need to re-run the cell? Or is this the first time you're attempting to use qgrid and you've never seen it work before?

If re-running the cell doesn't solve it for you, could you send me the output of `jupyter nbextension list`? 

Also did you try creating a new virtual env and doing a fresh install of qgrid? You can do that with the following 3 commands if you use virtualenv:
```
mkvirtualenv qgrid-test -p $(which python3)
pip install qgrid==1.0.0b10
jupyter nbextension enable --py --sys-prefix qgrid
```
Thanks.

**Comment by stef30360** [comment]
Hi, 
It works on jupyter notebook, but not in IDE Spyder notebook (https://github.com/spyder-ide/spyder-notebook) it's a shame.
thks

**Comment by TimShawver** [comment]
OK good to know.  Sorry to hear it doesn't work with Spyder...I hadn't heard of that actually so it's not something I've tested.

**Comment by stef30360** [comment]
Happy New Years Tim !
