### ISSUE TITLE
DataGrid width not tied to browser window width

### ISSUE THREAD

**Issue by slavi** [quantopian/qgrid#12]
Fantastic project, my team's been meaning to create something like this for months now. Kudos!!

The DataFrames we're working with tend to have many columns (100+). Currently, when I render a qgrid it looks like this:

![screen shot 2014-10-14 at 11 06 16 am](https://cloud.githubusercontent.com/assets/130298/4627298/c550827c-5389-11e4-8175-c0ed0b3e0e2a.png)

It would be great for us to have an option that does not limit the qgrid width to your browser, and instead overflows horizontally. You'd still see all columns, but you'd need to scroll (like in Excel).

**Comment by telson** [comment]
Hi @TimShawver ,
Is this issue in progress? 
Thanks @slavi for raising it.  I'm quite surprised more people aren't following this.

**Comment by TimShawver** [comment]
Hi @telson, we have an open PR https://github.com/quantopian/qgrid/pull/23 which will allow people to pass SlickGrid options in to change the behavior of the grid.  Specifically that will allow people to set SlickGrid's 'forceFitColumns' option to false to allow a scroll bar to appear (rather than trying to fit all the columns).  There was some back and forth and it got forgotten, so thanks for reminding me.  I'll resolve the open questions and merge it at some point this week (or maybe over the weekend).

**Comment by telson** [comment]
Hey @TimShawver ,  Great, Looking forward to it.!

**Comment by TimShawver** [comment]
@telson and @slavi, I merged a PR today so you now can achieve the desired behavior by setting grid_options like this:
```
qgrid.set_defaults(grid_options={
    'forceFitColumns': False,
    'defaultColumnWidth': 150
})
```
The set_defaults function sets the options for the grid for the lifetime of the kernel.  You can also set grid_options for individual grids by passing them in to the show_grid functions, like this:
```
qgrid.show_grid(spy, remote_js=False, grid_options={
    'forceFitColumns': False,
    'defaultColumnWidth': 150
})
```
Use the question mark operator to see the doc strings about these new capabilities:
```
qgrid.set_defaults?
qgrid.set_grid_option?
qgrid.show_grid?
```
forceFitColumns and defaultColumnWidth are just two of the SlickGrid options that can be set this way.  Here's the full list https://github.com/mleibman/SlickGrid/wiki/Grid-Options

Big thanks to @snth and @ssanderson for this awesome PR.  We haven't yet updated our package on PyPI, so if you won't be able to get the updated version with pip yet.  I'll do that tomorrow, but until then you'll have to just pull the latest from this repository to get the new capabilities.
