### ISSUE TITLE
Rendering not interactive

### ISSUE THREAD

**Issue by frivasa** [quantopian/qgrid#127]
Hello,
I've found some odd behavior since I reinstalled qgrid on a fresh miniconda(py27) instalation.
My notebook works fine right until the show_grid command, which renders nothing except if I use the 
option {'enableAddRow': True} which renders the add/remove row and export table buttons. If I click on the export, it renders the table and I can filter and scroll through it, but can't edit the entries even if I specifically add the {'editable':True} keyword to the options.

My relevant packages from conda list are:
ipykernel                 4.6.1                    py27_0    conda-forge
ipython                   5.4.1                    py27_0    conda-forge
ipywidgets                7.0.0                    py27_1    conda-forge
notebook                  5.0.0                    py27_0    conda-forge
pandas                    0.20.3                   py27_1    conda-forge

some noteworthy jupyter notebook --debug lines are:
[NotebookApp] Loaded config file: $home/miniconda3/envs/iceage/etc/jupyter/jupyter_notebook_config.json
[NotebookApp] Loaded config file: $home/.jupyter/jupyter_notebook_config.json
[NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20170913215009 (127.0.0.1) 4.02ms referer=the qgrid calling notebook

**Comment by TimShawver** [comment]
This probably caused by https://github.com/quantopian/qgrid/issues/129, since you're using ipywidgets 7.  I have a new version which should work for you, please see my comment on that other issue for information on how to install it: https://github.com/quantopian/qgrid/issues/129#issuecomment-332706796

**Comment by frivasa** [comment]
Yup, that was it.
`pip install qgrid==1.0.0b3`
`jupyter nbextension enable --py --sys-prefix qgrid`
worked for me since the conda install asks for python 3.

TY!
