### ISSUE TITLE
qgrid not compatible with ipywidgets 7.x

### ISSUE THREAD

**Issue by TimShawver** [quantopian/qgrid#129]
ipywidgets 7.x has some big changes in it which means qgrid is not compatible with it yet.  I have a 7.x compatible branch that I'll be merging soon, but in the meantime please use qgrid with ipywidgets 6.x.

**Comment by pgeez** [comment]
@TimShawver is the branch available anywhere?

**Comment by cchuang2009** [comment]
Try to install from pypi
qgrid-1.0.0a23

It works for my Mac box with Python-3.6.1 and ipywidgets-7.0.1

Wishes

**Comment by TimShawver** [comment]
@pgeez @cchuang2009 sorry about the delay, had a bunch of bugs I wanted to iron out before pointing people to the new version.  It's not merged yet but I think it's in pretty good shape at this point.  Installation instructions have changed slightly...you can see the new instructions in the README for my branch here:
https://github.com/quantopian/qgrid/tree/widget-guidelines

The short version is install and enable the new version with pypi:
```
pip install qgrid==1.0.0b3
jupyter nbextension enable --py --sys-prefix qgrid
```
Or with conda:
```
conda install -c tim_shawver/label/dev qgrid==1.0.0b3
```

Some other important links from that README:
- New demo notebook on binder https://beta.mybinder.org/v2/gh/quantopian/qgrid-notebooks/master?filepath=index.ipynb
- Updated API docs here: http://qgrid.readthedocs.io/en/widget-guidelines/

This was a big change so there will likely be some bugs initially.  Feel free to file issues (and specify that you're using the new beta) or reply to this issue with any feedback you might have.

**Comment by jdreaver** [comment]
@TimShawver I was having lots of trouble getting qgrid to work recently, but after wiping my conda env and installing your beta version everything worked perfectly. Thanks!

**Comment by TimShawver** [comment]
My branch has been merged to master, so I'm closing this. See the installation instructions on the [updated readme page](https://github.com/quantopian/qgrid#installation) to try it out.
