### ISSUE TITLE
Cannot reduce widget width beyond 60%

### ISSUE THREAD

**Issue by andymcarter** [quantopian/qgrid#130]
I am building up a dashboard of widgets built on a pandas dataframe model on Chrome. I would like to use the qgrid widget but I need to be able to shrink the dataframe down to around 30% width in a HBox.

If I set a ipyw.Layout after the qgrid widget is created, I am able to reduce the widget width down to around 60%, but no further. Setting a width of 30% does not shrink the dataframe any more than 60%.

I have tried to use the grid_options dict to specify defaultColumnWidth. This shrinks the columns but still leaves a 'frame' around the widget the original size.

Is it possible to have a 30% width grid widget?

```python
import numpy as np
import pandas as pd
import qgrid
import ipywidgets as ipyw
randn = np.random.randn
df_types = pd.DataFrame(np.random.randint(1,14,14))
qgrid_widget = qgrid.QgridWidget(df=df_types, show_toolbar=False)
qgrid_widget.layout = ipyw.Layout(width='100%')
qgrid_widget
```
![image](https://user-images.githubusercontent.com/22293319/31538468-914a02d6-affd-11e7-803c-d73755cd7bde.png)

```python
qgrid_widget.layout = ipyw.Layout(width='60%')
```

![image](https://user-images.githubusercontent.com/22293319/31538521-bff2d7d4-affd-11e7-864a-58e890d398ff.png)

```python
qgrid_widget.layout = ipyw.Layout(width='30%')
```
![image](https://user-images.githubusercontent.com/22293319/31538486-a0fb5856-affd-11e7-93f4-67cf0f08bb36.png)

```python
print(pd.__version__)
print(np.__version__)
print(ipyw.__version__)
print(qgrid.__version__)

0.20.3
1.13.1
7.0.1
1.0.0b3
```

**Comment by TimShawver** [comment]
Hi @andymcarter thanks for the report.  Looks like I had a min-width set on one of the elements wrapping qgrid, but it wasn't necessary so I've removed it.  I've released a new beta with this fix (beta 4).

Install and enable the new version with pypi:
```
pip install qgrid==1.0.0b4
jupyter nbextension enable --py --sys-prefix qgrid
```
Or with conda:
```
conda install -c tim_shawver/label/dev qgrid==1.0.0b4
```
