### ISSUE TITLE
resizing a column of a rendered widget automatically sorts the grid by that column

### ISSUE THREAD

**Issue by akapocsi** [quantopian/qgrid#134]
This is not the expected behavior, especially when it locks up the widget, e.g. #133

**Comment by TimShawver** [comment]
Thanks...should have a fix later this week or next week.

**Comment by TimShawver** [comment]
The fix has been merged and released in beta 8 (which you can get by uninstalling and reinstalling qgrid).  I'm going to close this for now but feel free to reopen it if the new version doesn't work for you.  Thanks.
