### ISSUE TITLE
Filter and Search produces incorrect filter

### ISSUE THREAD

**Issue by javierorozco** [quantopian/qgrid#135]
After entering a string in the search box within a column's filter, the list options are shorten to the check-box matching the searched item, then after checking the item outputted by the search, you end-up actually filtering by a different item than the one you searched for, see images. Then, Step 3 shows how the dataframe was filtered by other value different to the one selected from the search.
![qgrid_search](https://user-images.githubusercontent.com/5426388/31830680-daed6868-b5b8-11e7-962d-3fff1385f5fb.png)

**Comment by TimShawver** [comment]
OK thanks for the report, I should have a fix for this in the next beta.  Hopefully later this week or next week.

**Comment by TimShawver** [comment]
Fixes has been merged and releases in beta 8.  Please give the new version a shot and reopen the issue if it's not fixed.  Thanks.
