### ISSUE TITLE
qgrid 1.0

### ISSUE THREAD

**Issue by rgbkrk** [quantopian/qgrid#138]
When are you expecting to jump out of prerelease mode and onto a 1.0 release?

**Comment by TimShawver** [comment]
I'm on vacation until Sunday but I'm planning on spending some time addressing the issues people have found once I'm back.  Hard to say for sure how long that will take but I think there's a good chance I'll be able to finish those fixes (and create a 1.0 release) before the end of November.

**Comment by TimShawver** [comment]
Finally made the jump out of prerelease mode. Let me know if you have any questions/issues.  Last thing I was planning on doing for 1.0 was adding the conda packages to conda-forge, but they're available on my personal channel in the meantime.

**Comment by rgbkrk** [comment]
All good, for better or worse we're exclusively on `pip` for python packages at Netflix.
