### ISSUE TITLE
store the filtered grid in new dataframe

### ISSUE THREAD

**Issue by dacoex** [quantopian/qgrid#14]
Hello,
 is this scenario possible:

df_new = qgrid.show_grid(df, remote_js = True)

plt.scatter(df_new.index, dataframe['Col'])

In the essence, it would be great to have the df_new and the plot created from it updated interactively.

**Comment by TimShawver** [comment]
Not possible yet, but that's a cool idea.  Soon you'll be able to edit the values in the data frame thanks to this pull request: https://github.com/quantopian/qgrid/pull/27 but filters don't cause rows to be added/removed from the data frame.

**Comment by TimShawver** [comment]
Hi @dacoex, what you're asking for is almost possible now.  `show_grid` is a convenience function, and in the latest version of qgrid you can use the widget object directly to render a qgrid, like so:
```
from IPython.display import display
grid = qgrid.QGridWidget(df=spy)
display(grid) #alternative to show_grid
```
This would allow you get the underlying DataFrame object using `grid.df` and then you could pass it into your plot function as you did with `df_new` in your example.  The only problem left is I doubt that your plotting library would automatically pick up on the edits to the DataFrame until you rerun the cell to generate the plot again.  So I think you'll find that after you make edits, you'll need to execute the cell with the `scatter` function again to re-plot the DataFrame.  

I'm sure it's possible to automate that but it would be specific to the plotting library.  For that reason I don't think it's a problem that would be worthwhile for this project, so I'm closing this as fixed.

**Comment by dacoex** [comment]
thanks!.
