### ISSUE TITLE
column order

### ISSUE THREAD

**Issue by FrapiFrance** [quantopian/qgrid#140]
df = pandas.DataFrame(dic_for_pandas, columns= sorted(dic_for_pandas.keys()))

Without qgrid, columns are printed in the correct order

With qgrid, column order seems garbled ?

**Comment by vkhombal** [comment]
I have the same problem.

**Comment by vkhombal** [comment]
the column reordering works and may be a workable alternative.

**Comment by TimShawver** [comment]
Hmm I haven't been able to reproduce this yet.  Here's an example where I reverse the sort and qgrid seems to show the columns in the correct order:
![screen shot 2017-11-09 at 8 55 28 pm](https://user-images.githubusercontent.com/5055866/32639146-72d9f722-c590-11e7-8422-75fcbdf2c6f9.png)

What version of pandas are you using? And could you send code for a sample data frame that reproduces the problem? Thanks.

**Comment by vcxz09876** [comment]
The problem is only, when all install via pip3.
If install via conda problem not reproduced.

**Comment by TimShawver** [comment]
Hmm weird. I installed via pip too and I couldn't reproduce it.  Is it possible you have an older beta of qgrid installed in your virtualenv? If you type `pip show qgrid` you should see the version listed as `1.0.0b7`.

**Comment by vkhombal** [comment]
I still see this.
```
MAC:~ vh$ pip show qgrid
Name: qgrid
Version: 1.0.0b7
Summary: An Interactive Grid for Sorting and Filtering DataFrames in Jupyter Notebook
Home-page: https://github.com/quantopian/qgrid
Author: Quantopian Inc.
Author-email: tshawver@quantopian.com
License: UNKNOWN
Location: /Users/vh/anaconda/lib/python3.5/site-packages
Requires: pandas, ipywidgets, notebook
```

**Comment by gmatefi** [comment]
I've faced this issue as well with qgrid-1.0.0.b8. Looking into the code, the problem is caused by using dictionary data type for sending the column definitions to JS front-end, which does not preserve item ordering. A quick prototype with using ordered list instead fixed the problem.

**Comment by TimShawver** [comment]
Thanks @gmatefi, I'll make the fix and create a new release soon, most likely later this week or this weekend.
