### ISSUE TITLE
Filtering by Multi-Index Column Results in Wrong Rows Selected

### ISSUE THREAD

**Issue by dragoljub** [quantopian/qgrid#144]
When running the example below. Type in 'unit' in the country column and select United States. The selected rows are incorrectly Algeria. Probably issue with Multi-Index section after fuzzy search reduction.

```
import qgrid
import pandas as pd
from pandas_datareader import wb
df_countries = wb.download(indicator='NY.GDP.PCAP.KD', country=['all'], start=2005, end=2008)
df_countries.columns = ['GDP per capita (constant 2005 US$)']
qgrid.show_grid(df_countries)
```

![image](https://user-images.githubusercontent.com/2701562/32798535-db0e1c6e-c929-11e7-95e9-74415d6814c1.png)

**Comment by TimShawver** [comment]
Thanks...this sounds like the same issue as https://github.com/quantopian/qgrid/issues/135.  I've started working on it but haven't quite finished yet.  Should have a fix (and a new beta release) in the next week or so.

**Comment by dragoljub** [comment]
Cool I'll check back next week. Thanks! qgrid is starting to look really good. 👍
