### ISSUE TITLE
Filter selects wrong items

### ISSUE THREAD

**Issue by Cazimodo** [quantopian/qgrid#145]
![qgrid filter issue](https://user-images.githubusercontent.com/376797/32852105-a4ea9218-ca3f-11e7-816b-90e3971eb827.gif)

To reproduce:
1. Go to demo binder as per your github readme: https://beta.mybinder.org/v2/gh/quantopian/qgrid-notebooks/master?filepath=index.ipynb
2. Scroll to example 4
3. Execute the cell which displays the qgrid country GDP
4. Click Filter icon for Country column
5. Type in 'South' to filter the list down to 'South Africa'
6. Click tick box next to South Africa
7. Notice that the qgrid then displays gdp for Afghanistan rather than South Africa. Now while our economy is being ransacked by the powers that be I'd hope we're doing a bit better than Afghanistan :)
8. Just scrolling down to South Africa and selecting it works fine

**Comment by TimShawver** [comment]
Thanks for the report...this sounds like the same issue as https://github.com/quantopian/qgrid/issues/145.  I'm working on a fix today and I expect to release a new beta with that fix by EOD tomorrow (Sunday).

**Comment by Cazimodo** [comment]
Hmmm, I suspect you meant this is a duplicate of another issue. this IS issue #145. Closest one I could find with my limited knowledge of qgrid is #137

**Comment by TimShawver** [comment]
Sorry, yea I copied the wrong URL, I meant https://github.com/quantopian/qgrid/issues/135.

**Comment by TimShawver** [comment]
The fix has been merged and released in beta 8 (which you can get by uninstalling and reinstalling qgrid).  I'm going to close this for now but feel free to reopen it if the new version doesn't work for you.  Thanks.
