### ISSUE TITLE
Data columns named 'id' get replaced by row number

### ISSUE THREAD

**Issue by avdempsey** [quantopian/qgrid#15]
If your DataFrame has a column named 'id' it will be replaced with a column of values like: 'row0', 'row1', etc.

Renaming the column before displaying with show_grid() solves the issue.

![screen shot 2015-01-05 at 5 05 54 pm](https://cloud.githubusercontent.com/assets/465105/5622790/0a753054-94fe-11e4-94b1-7c7fa3fe3190.png)

**Comment by djchou** [comment]
Fixed, See pull request #38
