### ISSUE TITLE
Cannot install on jupyter .5.3.1 from Conda

### ISSUE THREAD

**Issue by dartdog** [quantopian/qgrid#166]
See initial error on setup from conda followed by an attempt at a diagnostic run with all system info dumped. It may be a conda issue?

Package plan for installation in environment /home/tom/anaconda3:

The following NEW packages will be INSTALLED:

    qgrid: 1.0.0-py36_0 tim_shawver

Proceed ([y]/n)? y

qgrid-1.0.0-py 100% |################################| Time: 0:00:00   1.58 MB/s
ERROR conda.core.link:_execute_actions(339): An error occurred while installing package 'tim_shawver::qgrid-1.0.0-py36_0'.
LinkError: post-link script failed for package tim_shawver::qgrid-1.0.0-py36_0
running your command again with `-v` will provide additional information
location of failed script: /home/tom/anaconda3/bin/.qgrid-post-link.sh
==> script messages <==
<None>

Attempting to roll back.

LinkError: post-link script failed for package tim_shawver::qgrid-1.0.0-py36_0
running your command again with `-v` will provide additional information
location of failed script: /home/tom/anaconda3/bin/.qgrid-post-link.sh
==> script messages <==
<None>
tom@tomServal:~$ conda install -v tim_shawver qgrid 
Fetching package metadata ...............
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.32
       conda is private : False
      conda-env version : 4.3.32
    conda-build version : not installed
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /home/tom/anaconda3  (writable)
    default environment : /home/tom/anaconda3
       envs directories : /home/tom/anaconda3/envs
                          /home/tom/.conda/envs
          package cache : /home/tom/anaconda3/pkgs
                          /home/tom/.conda/pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/linux-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/tom/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.32 requests/2.18.4 CPython/3.6.3 Linux/4.13.0-26-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000

`$ /home/tom/anaconda3/bin/conda install -v tim_shawver qgrid`

    Traceback (most recent call last):
      File "/home/tom/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 261, in install
        channel_priority_map=_channel_priority_map, is_update=isupdate)
      File "/home/tom/anaconda3/lib/python3.6/site-packages/conda/common/io.py", line 174, in decorated
        return f(*args, **kwds)
      File "/home/tom/anaconda3/lib/python3.6/site-packages/conda/plan.py", line 478, in install_actions_list
        dists_for_envs = determine_all_envs(r, specs, channel_priority_map=channel_priority_map)
      File "/home/tom/anaconda3/lib/python3.6/site-packages/conda/plan.py", line 543, in determine_all_envs
        spec_for_envs = tuple(SpecForEnv(env=p.preferred_env, spec=p.name) for p in best_pkgs)
      File "/home/tom/anaconda3/lib/python3.6/site-packages/conda/plan.py", line 543, in <genexpr>
        spec_for_envs = tuple(SpecForEnv(env=p.preferred_env, spec=p.name) for p in best_pkgs)
      File "/home/tom/anaconda3/lib/python3.6/site-packages/conda/plan.py", line 542, in <genexpr>
        best_pkgs = (r.index[r.get_dists_for_spec(s, emptyok=False)[-1]] for s in specs)
      File "/home/tom/anaconda3/lib/python3.6/site-packages/conda/resolve.py", line 565, in get_dists_for_spec
        raise ResolvePackageNotFound([(ms,)])
    conda.exceptions.ResolvePackageNotFound: 
      - tim_shawver
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/tom/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/tom/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/home/tom/anaconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/tom/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 275, in install
        raise PackageNotFoundError(pkg, channels_urls)
    conda.exceptions.PackageNotFoundError: Packages missing in current channels:
                
      - tim_shawver
    
    We have searched for the packages in the following channels:
                
      - https://conda.anaconda.org/anaconda-fusion/linux-64
      - https://conda.anaconda.org/anaconda-fusion/noarch
      - https://conda.anaconda.org/conda-forge/linux-64
      - https://conda.anaconda.org/conda-forge/noarch
      - https://repo.continuum.io/pkgs/main/linux-64
      - https://repo.continuum.io/pkgs/main/noarch
      - https://repo.continuum.io/pkgs/free/linux-64
      - https://repo.continuum.io/pkgs/free/noarch
      - https://repo.continuum.io/pkgs/r/linux-64
      - https://repo.continuum.io/pkgs/r/noarch
      - https://repo.continuum.io/pkgs/pro/linux-64
      - https://repo.continuum.io/pkgs/pro/noarch

**Comment by TimShawver** [comment]
Interesting...yea the error seems to say that the post-link step is failing. The post-link step enables qgrid by running `jupyter nbextension enable --py --sys-prefix qgrid`.  Unfortunately I don't think running that step manually will work as a workaround though, because when the post-link step fails conda attempts to rollback your environment to it's original state. I'm not 100% sure about that though so you could give it a shot.

Regarding your second attempt to use the `-v` flag, looks like the reason it didn't work is because you left out the `-c` flag.  I think the command you want to run there is `conda install -v -c tim_shawver qgrid`.  Hopefully that provides some useful logging.

Have you tried installing qgrid from scratch in a new conda environment? That often clears up these sorts of problems that seem potentially environment-specific.

**Comment by dartdog** [comment]
I definitely had some deep Jupyter issues new release of notebook forthcoming 5.3.2 Close this unless I reopen, sorry..
