### ISSUE TITLE
JupyterLab Widget doesn't resize

### ISSUE THREAD

**Issue by dhirschfeld** [quantopian/qgrid#167]
When the width of the JupyterLab panel resizes the qgrid doesn't resize to fit.

Also, when `forceFitColumns=True` and the JupyterLab panel is resized smaller so the grid doesn't fit the new width no horizontal scrollbar appears.

```
JupyteLab 0.31.2
qgrid 1.0.1b0
```

**Comment by TimShawver** [comment]
Thanks, I have a fix for this working locally and I'll include it in the next release.  In the meantime, when qgrid's size get's messed up, you can resize your browser window to make qgrid resize itself.

**Comment by TimShawver** [comment]
This should be fixed in version 1.0.1 which has now been released. Thanks again for reporting this and feel free to reopen if the fix doesn't work for you.
