### ISSUE TITLE
conda package for python=3.5

### ISSUE THREAD

**Issue by sergun** [quantopian/qgrid#168]
Hi Tim!

Will you prepare qgrid=1.0.0 conda package for python=3.5

Or you will support only python=2.7 and 3.6 inside conda?

**Comment by TimShawver** [comment]
Hi, I didn't realize people used 3.5...I can try and do that next time I do a conda release. Thanks for the info.

**Comment by TimShawver** [comment]
Qgrid's conda packages are now being built by conda-forge, and the conda-forge build covers python 3.5, so this should be available on the conda-forge channel now.  Installation is as follows:
```
# only required if you have not added conda-forge to your channels yet
conda config --add channels conda-forge

conda install qgrid
```
Feel free to reopen if you run into any issues and thanks again for the report.
