### ISSUE TITLE
qgrid is not correctly resizing when it is unhidden inside of an accordion widget

### ISSUE THREAD

**Issue by cdknorow** [quantopian/qgrid#169]
When placing a qgrid inside of an Accordion widget which is not initially shown, qgrid columns are not properly resized when the qgrid accordion tab is selected. This issue most likely has to do with qgrid not resizing when its state is changed from hidden to visible. The columns are correctly resized by resizing the window or alternatively resetting the qgrid df.

Example. 
grid = show_grid(df)
accordion= Accordion(children=[grid])
accordion.selected_index = None

when you click the accordion tab, qgrid columns will be sized incorrectly.

If I resize the window, or reset qgrid.df the columns are correctly set again.

grid.df = grid.df

**Comment by TimShawver** [comment]
Thanks, haven't had time to look at this yet but sounds like it's worth fixing.

**Comment by TimShawver** [comment]
I have a fix for this and I'm going to include it in the next release.

**Comment by TimShawver** [comment]
This should be fixed in version 1.0.1 which has now been released. Thanks again for reporting this and feel free to reopen if the fix doesn't work for you.
