### ISSUE TITLE
No horizontal scrollbar and all columns are squeezed together 

### ISSUE THREAD

**Issue by zhiruiwang** [quantopian/qgrid#171]
### Environment

* Operating System: macOS High Sierra 10.13.3 
* Python Version: 3.6.4
* How did you install Qgrid: conda
* Python packages:   
notebook                  5.4.0 
qgrid                     1.0.0

### Description of Issue

When I use qgrid to visualize a pandas DataFrame with many columns, the qgrid widget fails to produce a horizontal scroll bar, thus all columns are squeezed together in order to fit into the screen.

### Reproduction Steps

```
import pandas as pd
import urllib
import pickle
url = 'https://raw.githubusercontent.com/udacity/ud120-projects/master/final_project/final_project_dataset.pkl'
enron_data = pickle.load(urllib.request.urlopen(url))
enron_data = pd.DataFrame(enron_data).transpose()
enron_data.head()
```
![](https://image.ibb.co/fQrP87/Screen_Shot_2018_02_14_at_10_53_34_AM.png)

```
import qgrid
qgrid.show_grid(enron_data)
```
![](https://image.ibb.co/cv4Nvn/Screen_Shot_2018_02_14_at_10_56_32_AM.png)

**Comment by TimShawver** [comment]
You can set the `forceFitColumns` option to `False` to show a horizontal scrollbar.  You can also use `defaultColumnWidth` option to set the starting width of your columns (in pixels). The options are set via the `grid_options` kwarg that `show_grid` takes.

In your case, you could use it like this:
```
qgrid.show_grid(enron_data, grid_options={'forceFitColumns': False, 'defaultColumnWidth': 100})
```

**Comment by zhiruiwang** [comment]
Thanks Tim, this is really helpful!

**Comment by kingjr** [comment]
@TimShawver Thanks, is there a way to automatically adjust each column's width as a function of its content (e.g. small width if contains small strings; large width if contains long strings)?

**Comment by RCarrasco1** [comment]
Hello Tim.  Awesome tool qgrid.  Can I save a filtered DataFrame after modified in qgrid?
Regards

**Comment by berndtlindner** [comment]
RCarrasco1  on your question you can `get_changed_df()` on the qgrid table displayed,
i.e.
```
widget_qgrid = qgrid.show_grid(df)
```
_user makes changes_
```
widget_qgrid.get_changed_df()
```
