### ISSUE TITLE
Cannot change cell value to 0 by double clicking

### ISSUE THREAD

**Issue by n4562** [quantopian/qgrid#174]
Hello,

I.e. rendering a Qgrid, double clicking one cell, inputting 0 won't update the cell value (it'll keep the previous value).

Thanks,

**Comment by TimShawver** [comment]
Ouch, sorry about that.  I'll take a look at this ASAP, should be a quick fix.

**Comment by TimShawver** [comment]
I've uploaded a new beta version to pypi, called `1.0.2b0`.  You can install it with: 
```
pip install qgrid --pre
jupyter nbextension enable --py --sys-prefix qgrid
```
I'll also be creating an official release and uploading it to conda soon.
