### ISSUE TITLE
Error in displaying widget in JupyterLab 0.31.8

### ISSUE THREAD

**Issue by fretchen** [quantopian/qgrid#180]
### Environment

* Operating System: MacOS 10.13
* Python Version: 3
* How did you install Qgrid:  `conda`
* Python packages: `$ pip freeze` or `$ conda list` (please include qgrid, notebook, and jupyterlab versions)
appnope                   0.1.0                    py36_0    conda-forge
bleach                    2.0.0                      py_1    conda-forge
ca-certificates           2017.08.26           ha1e5d58_0  
certifi                   2018.1.18                py36_0  
cycler                    0.10.0           py36hfc81398_0  
decorator                 4.1.2                    py36_0    conda-forge
entrypoints               0.2.3                    py36_1    conda-forge
freetype                  2.8                  h12048fb_1  
html5lib                  1.0.1                      py_0    conda-forge
intel-openmp              2018.0.0             h8158457_8  
ipykernel                 4.8.2                    py36_0    conda-forge
ipython                   6.2.1                    py36_1    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
ipywidgets                7.1.2                    py36_0  
jedi                      0.11.1                   py36_0    conda-forge
jinja2                    2.10                     py36_0    conda-forge
jsonschema                2.6.0                    py36_1    conda-forge
jupyter_client            5.2.2                    py36_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                0.31.8                   py36_1    conda-forge
jupyterlab-latex          0.2.0                     <pip>
jupyterlab_launcher       0.10.5                   py36_0    conda-forge
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libedit                   3.1                  hb4e282d_0  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libpng                    1.6.34               he12f830_0  
libsodium                 1.0.15                        1    conda-forge
markupsafe                1.0                      py36_0    conda-forge
matplotlib                2.1.2            py36h6d6146d_0  
mistune                   0.8.3                      py_0    conda-forge
mkl                       2018.0.1             hfbd8650_4  
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                    py36_0    conda-forge
ncurses                   6.0                  hd04f020_2  
nodejs                    8.9.3                h378b8a2_0  
notebook                  5.4.0                    py36_0    conda-forge
numpy                     1.14.1           py36h8a80b8c_1  
openssl                   1.0.2n               hdbc3d79_0  
pandas                    0.22.0           py36h0a44026_0  
pandoc                    2.1.1                         0    conda-forge
pandocfilters             1.4.1                    py36_0    conda-forge
parso                     0.1.1                      py_0    conda-forge
pexpect                   4.4.0                    py36_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pip                       9.0.1            py36h1555ced_4  
prompt_toolkit            1.0.15                   py36_0    conda-forge
ptyprocess                0.5.2                    py36_0    conda-forge
pygments                  2.2.0                    py36_0    conda-forge
pyparsing                 2.2.0            py36hb281f35_0  
python                    3.6.4                hc167b69_1  
python-dateutil           2.6.1                    py36_0    conda-forge
pytz                      2018.3                   py36_0  
pyzmq                     17.0.0                   py36_3    conda-forge
qgrid                     1.0.1                    py36_1  
readline                  7.0                  hc1231fa_4  
scipy                     1.0.0            py36h1de22e9_0  
send2trash                1.5.0                      py_0    conda-forge
setuptools                38.5.1                   py36_0  
simplegeneric             0.8.1                    py36_0    conda-forge
six                       1.11.0                   py36_1    conda-forge
sqlite                    3.22.0               h3efe00b_0  
terminado                 0.8.1                    py36_0    conda-forge
testpath                  0.3.1                    py36_0    conda-forge
tk                        8.6.7                h35a86e2_3  
tornado                   4.5.3                    py36_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
wcwidth                   0.1.7                    py36_0    conda-forge
webencodings              0.5                      py36_0    conda-forge
wheel                     0.30.0           py36h5eb2c71_1  
widgetsnbextension        3.1.4                    py36_0  
xz                        5.2.3                h0278029_2  
zeromq                    4.2.3                         2    conda-forge
zlib                      1.2.11               hf3cbc9b_2 

* Jupyter lab packages (if applicable): `$ jupyter labextension list`
JupyterLab v0.31.8
Known labextensions:
   app dir: /Users/fnj/miniconda2/envs/JLenv2/share/jupyter/lab
@jupyter-widgets/jupyterlab-manager
        @jupyter-widgets/jupyterlab-manager v0.33.2  enabled  OK
@jupyterlab/latex
        @jupyterlab/latex v0.2.0  enabled  OK
qgrid
        qgrid v1.0.2  enabled  OK

### Description of Issue

* I tried to start the installation of the grid as described. While running the installation script
> jupyter labextension install qgrid

I obtain the following error:

WARNING in ./~/qgrid/src/qgrid.widget.js
Module not found: Error: Can't resolve 'base/js/dialog' in '.../envs/JLenv2/share/jupyter/lab/staging/node_modules/qgrid/src'
 @ ./~/qgrid/src/qgrid.widget.js 12:11-36
 @ ./~/qgrid/src/index.js
 @ ./~/qgrid/src/jupyterlab-plugin.js
 @ ./build/index.out.js
 @ multi whatwg-fetch ./build/index.out.js

* What happened instead?
 Then running the example code of the binder:

```
import numpy as np
import pandas as pd
import qgrid
randn = np.random.randn
df_types = pd.DataFrame({
    'A' : 1.,
    'B' : pd.Series(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06', '2013-01-07', '2013-01-08', '2013-01-09'],index=list(range(9)),dtype='datetime64[ns]'),
    'C' : pd.Series(randn(9),index=list(range(9)),dtype='float32'),
    'D' : np.array([3] * 9,dtype='int32'),
    'E' : pd.Categorical(["washington", "adams", "washington", "madison", "lincoln","jefferson", "hamilton", "roosevelt", "kennedy"]),
    'F' : ["foo", "bar", "buzz", "bippity","boppity", "foo", "foo", "bar", "zoo"] })
df_types['G'] = df_types['F'] == 'foo'
qgrid_widget = qgrid.QgridWidget(df=df_types, show_toolbar=True)
qgrid_widget
```

This results in:

> Error displaying widget

**Comment by AlexCid** [comment]
I have the same error message, but in a different setup:

- OS: Ubuntu 16.04 LTS
- qgrid v1.0.1 installed via pip
- Python version: 3.5.2
- JupyterLab v0.31.12
- jupyterlab-manager v0.33.2

It turned out that I install qgrid v1.0.**1** via qgrid, but somehow jupyterlab showed me version 1.0.**2**. After updating my qgrid version, installed via pip, to 1.0.2 (and in general updating all my packets), the problem disappeared. I see that you installed 1.0.1 via conda but jupyterlab shows 1.0.2, so the solution might work for you too.

Cheers,

Alexander Schaub

**Comment by fretchen** [comment]
Running `pip install qgrid --upgrade` solved it indeed. Quite interestingly the problem did not exist on a Windows machine that we had around.

**Comment by TimShawver** [comment]
Good to hear...closing, as this appears to be resolved.
