### ISSUE TITLE
Widget not shown with Jupyter Lab 0.31.32 and qgrid 1.0.2

### ISSUE THREAD

**Issue by NicolaOrritos** [quantopian/qgrid#187]
### Environment

* Operating System: **Windows 10 64bit**
* Python Version: **Python 3.6.4 :: Anaconda custom (64-bit)**
* How did you install Qgrid: **conda**
* Python packages:
  - ...
  - jupyterlab                **0.31.12**                  py36_0
  - notebook                  **5.0.0**            py36hd9fbf6f_2
  - qgrid                     **1.0.2**                    py36_1
  - ...
* Jupyter lab packages (if applicable): -

### Description of Issue

* What did you expect to happen?
I expected the table widget to be shown on my notebook.
* What happened instead?
Text `A Jupyter Widget` gets displayed instead.

### Reproduction Steps

1. I installed qgrid and its lab-extension:
    ```Bash
    $ conda install qgrid
    $ jupyter labextension install qgrid
    ```

2. Imported a dataset, imported it into a DataFrame with Pandas, then took a subset of it:
    ```python
    from sklearn.datasets import load_boston
    import pandas as pd
    boston = load_boston()
    df = pd.DataFrame(boston['data'], columns=boston['feature_names'])
    hdf = df[:20]
    ```
2. Imported qgrid and used to display a `df` qgrid:
    ```python
    import qgrid
    qgrid.show_grid(hdf)
    ```

### What steps have you taken to resolve this already?
Checked whether qgrid version and qgrid notebook extension version were the same.  
Tried with a traditional Jupyter notebook in the same environment and with the same code and it works.  

### Anything else?

No.

**Comment by mimischi** [comment]
I just got it working with the newest version of JupyterLab (0.32.0):

```bash
notebook==5.4.1
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.0
jupyter-core==4.4.0
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.4
jupyter-nbextensions-configurator==0.4.0
jupyterlab==0.32.0
jupyterlab-launcher==0.10.5
qgrid==1.0.2
```

Had to fumble around a bit, but I think in the end it was:
1. `conda install -n base -c conda-forge widgetsnbextension`
2. `conda install -n <my-qgrid-environment> -c conda-forge ipywidgets`
3. `jupyter lab clean`
4. `jupyter labextension install @jupyter-widgets/jupyterlab-manager`
5. ` jupyter labextension install qgrid`

Points 1-4 I found in the ipywidgets documentation: https://ipywidgets.readthedocs.io/en/stable/user_install.html

**Comment by NicolaOrritos** [comment]
Well, a bit better, but still not working.
Now, when I execute the cell `qgrid.show_grid(hdf)` it displays the following:  
`QgridWidget(grid_options={'fullWidthRows': True, 'syncColumnCellResize': True, 'forceFitColumns': True, 'defau…`

I also have some errors in my Chrome console:
```
Uncaught (in promise) Error: Object 'jupyter.widget' not found in registry
    at default.js:1443
    at new Promise (<anonymous>)
    at Object.C [as loadObject] (default.js:1422)
    at e._handleCommOpen (default.js:913)
    at WebSocket._onWSMessage (default.js:136)
```

**Comment by NicolaOrritos** [comment]
I think I found the issue: it's the labextension "jupyterlab-manager" that cannot be installed, thus invalidating the subsequent steps of your fix @mimischi.  
And there is no way to fix the installation problems of this version of the jupyter-manager, as per [this thread](https://github.com/jupyterlab/jupyterlab/issues/3215).

Sad

**Comment by TimShawver** [comment]
Hmm sorry to hear that, hopefully you can install another version.  

Just to clarify for other readers this sounds like a compatibility problem between jupyterlab and a specific version of the ipywidgets jupyterlab extension, which is not qgrid-specific. I'm going to close this since it's a general problem with the widgets framework that's not specific to qgrid.

**Comment by NicolaOrritos** [comment]
Well, thanks a lot for your help.  
I'll update this issue if I discover anything related to it, but I think you're right @TimShawver : definitely looks like an incompatibility between certain versions of the widgets and Jupyterlab.
