### ISSUE TITLE
Provide edit cell location after editing.

### ISSUE THREAD

**Issue by andyfaff** [quantopian/qgrid#189]
Currently one can observe that the dataframe has been edited by using:

```
def func(change):
    print(change)

q_gridwidget = qgrid.QgridWidget(df)
q_gridwidget.observe(func, '_df')
```

However, the function does not know the location (index/col) of the cell that was edited. This is known in the [code](https://github.com/quantopian/qgrid/blob/master/qgrid/grid.py#L912). Could the [_trigger_df_change_event](https://github.com/quantopian/qgrid/blob/master/qgrid/grid.py#L966) be sent that location (via keyword args) to include in the `Bunch` returned by that method?

I'm willing to submit a PR if that helps. My alternative is to subclass QGridWidget, but that seems a bit extreme.

**Comment by Robuko** [comment]
This would be very helpful, +1
