### ISSUE TITLE
Can't update _selected_rows from python

### ISSUE THREAD

**Issue by shenker** [quantopian/qgrid#206]
I'm wondering how to change the selected rows from Python. I couldn't figure out a way to propagate the `._selected_rows` attribute to the browser and have it update the table styling.

I want to synchronize the index of the selected row in a qgrid table with a Holoviews Stream. Right now I have the qgrid->Stream direction working (i.e., click on a row, and it updates the stream), but I'd like the reverse as well (i.e., whenever the stream updates, I want the highlighted row to change in the browser).

On Python 3.6.5, qgrid from git master, latest jupyterlab via pip.

**Comment by TimShawver** [comment]
Thanks for the suggestion...yea I think it makes perfect sense.  I'm planning on adding the "reverse" of the events API which would allow any of the qgrid interactions (including row selection) that are supported in the events API to be triggered programmatically from python code. Not sure when I'll get to it but it's one of the most requested features right now, so it's probably the next big enhancement to qgrid that I'll be making.

**Comment by TimShawver** [comment]
This features was added in qgrid 1.1.0, which is available on pypi and conda forge now.  See the API docs for information on the new `change_selection` method: http://qgrid.readthedocs.io/en/latest/#qgrid.QgridWidget.change_selection
