### ISSUE TITLE
Qgrid 1.1.* Only 100 rows visible and sorting and filtering do not work. 

### ISSUE THREAD

**Issue by vkhombal** [quantopian/qgrid#212]
### Environment

* Operating System:
* Python Version: `3.6.5`
* How did you install Qgrid: (`conda`)
* Python packages:
qgrid=1.1*
notebook=5.6.0

### Description of Issue

* What did you expect to happen?
sort columns, scroll to see all rows of a df 
* What happened instead?
In qgrid=1.1.0 and 1.1.1 only 100 rows are visible, scrolling down beyond 100 rows shows empty rows.

The UI hangs for both sorting and filtering (wheel keeps running) irrespective of the number of rows in the df.

### Reproduction Steps
import qgrid
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.rand(200, 10))
dd = qgrid.QgridWidget(df=df)
dd

### What steps have you taken to resolve this already?
Reverted to qgrid=1.0.5, where it behaves as expected.

**Comment by TimShawver** [comment]
Strange, I'm unable to reproduce this issue.  It almost sounds like the JS and the python side of the widget don't having matching versions, but I didn't realize that was possible.  

One troubleshooting step that I'd suggest if you haven't tried already would be to try creating a new virtual environment or conda environment and doing a fresh install of Qgrid.  Another thing you might try is clearing your browser cache in case it's caching an old version of Qgrid's javascript.

**Comment by vkhombal** [comment]
Thank you for the quick response.

The behavior reported above was based on a conda env with only ipykernel and qgrid. 

There is no no change in behavior with cleared Chrome cache.

[environment.txt](https://github.com/quantopian/qgrid/files/2207341/environment.txt)

**Comment by vkhombal** [comment]
@TimShawver 
I was able to resolve this issue by installing and enabling v1.1.1.

Thanks.

**Comment by healiseu** [comment]
Hi Tim, qgrid is a great open-source dataframe browser, thank you for sharing this with the rest of us. I had similar problems when I installed the new release of the software but they have gone away when I cleared browser cache. That is a good troubleshooting advice.
