### ISSUE TITLE
Show_grid shows Loading Widget forever

### ISSUE THREAD

**Issue by EricCacciavillani** [quantopian/qgrid#259]
### Environment

* Operating System: Mac Mojave (10.14.5)
* Python Version: `$ python 3.6`
* How did you install Qgrid: I have done both conda install and pip install.
* Python packages: [Pip Freeze.txt](https://github.com/quantopian/qgrid/files/3356356/Pip.Freeze.txt)
[JupterLab Extensions.txt](https://github.com/quantopian/qgrid/files/3356355/JupterLab.Extensions.txt)
(Which for whatever reason say that don't exist but I definitely put them in.)

<img width="1293" alt="Screen Shot 2019-07-03 at 2 21 50 PM" src="https://user-images.githubusercontent.com/16104771/60615818-0bceb300-9d9e-11e9-9e83-277e95b661b3.png">

### Description of Issue

* What did you expect to happen?

- I expected to see my DataFrame to be seen in the filter widget.

* What happened instead?

- It says "Loading widget..." (Also for whatever reason nbinstall doesn't exist on qgrid.)

### Reproduction Steps

1. Setting up a quick conda env with those dependencies in "Pip Freeze" 

### What steps have you taken to resolve this already?
1. Started multiple fresh environments.
2. Nuked all of my conda environments and got a clean install to find it still not working.
...
### Anything else?

I am trying to embed this into another project I am working on. By any chance can I get access to the features and there associated filtered values that are to create the new DataFrame?

Ex: 
Filtered Feature:
    Age:
-----"<":
----------60
-----">":
----------5
...

**Comment by Nestak2** [comment]
@EricCacciavillani Same problem here! Did you find a solution?

**Comment by EricCacciavillani** [comment]
Nope still having the same issue. I want to add this to workflow, but I can't seem to get it working correctly. I will keep trying to come back to this post; let me know if more people are also getting this error; maybe we can all come together and try to debug it : ). (Sorry in advance for not responding back @Nestak2 the I must have missed the notification.)

**Comment by EricCacciavillani** [comment]
I kind of love this other project I found: https://pypi.org/project/pandasgui/. In case anyone else who is having this problem would like to give it a shot.

**Comment by ajennings6767** [comment]
I'm having the same issue. Here is a bit of additional info:

![image](https://user-images.githubusercontent.com/30580411/71825078-12015d00-3069-11ea-97c3-f52c9178b2e1.png)

**Comment by jnissin** [comment]
I don't know if this helps anyone but I managed to get things working with QGrid 1.2.0 + JupyterLab 1.2.6. I installed qgrid and the labextension from the source by cloning the git respository and running:

`git clone https://github.com/quantopian/qgrid.git`
`cd qgrid && pip install . && jupyter labextension install js/`

However, before that I had to change the version number in the `js/package.json` from: `"version": "1.1.2"` to: `"version": "1.1.1"`. Installing the labextension from the source (as above) then fixed the error regarding the `semver range 1.1.1`. I have no idea why this fixes it, perhaps someone more educated in JupyterLab extensions can enlighten us? :)

**Comment by jnissin** [comment]
I continued the research. The same issue can be found for a bunch of other JupyterLab widgets and I think it is related to the widget version in `js/package.json` not matching with the `_model_module_version` and `_view_module_version` found in `js/src/qgrid.widget.js`. Originally the `js/package.json` contains version 1.1.2 whereas the versions in `js/src/qgrid.widget.js` are 1.1.1. I base this diagnosis on a similar [issue #95](https://github.com/jupyter-widgets/ipyleaflet/issues/95) I found in jupyter-leaflet. Seems like the solution is to make these versions match one way or the other.

**Comment by geiziry** [comment]
for windows had to include `shell=True` in setup.py for `check_call` to be able to detect npm,

**Comment by gerrymanoim** [comment]
I believe that the issue in https://github.com/quantopian/qgrid/issues/259#issuecomment-585806624 should no longer be present. Please reopen if you continue to have problems on the latest qgrid.

**Comment by apiedram** [comment]
Doesn't work for me. I have Mac OS X Capitan, Jupyter 1.2.6, and still displaying:

`Error displaying widget: model not found`

**Comment by iacisme** [comment]
I'm having this issue, Ubunty 20.04, Intel i7. Jupyter lab 3.x

I just installed qgrid using pip.
