### ISSUE TITLE
Error displaying widget: model not found on new Jupyter Lab

### ISSUE THREAD

**Issue by zhiwenchong** [quantopian/qgrid#271]
### Environment

* Operating System: Windows
* Python Version: `Python 3.6.6 :: Anaconda, Inc.`
* How did you install Qgrid: `pip`
* Jupyter lab packages (if applicable): 
```
JupyterLab v1.1.1
Known labextensions:
   app dir: c:\users\xxxx\.conda\envs\xxxx\share\jupyter\lab
        @jupyter-widgets/jupyterlab-manager v1.0.2 enabled  ok
        qgrid v1.1.1 enabled  ok
```

### Description of Issue
* What did you expect to happen?

Qgrid displays. This was working until I tried installing the latest version of jupyterlab-manager because I needed my notebook to work with ipywidgets.

* What happened instead?

Received error message `Error displaying widget: model not found`.

### Reproduction Steps

Run this code to receive error message (in Jupyter Lab 1.1.1)
```
import pandas as pd
import numpy as np
import qgrid

df = pd.DataFrame(np.random.rand(5,5))

gridopts = {"fullWidthRows": False,
            "autoEdit": True,
            "sortable": False,
            }
qgrid.show_grid(df, grid_options=gridopts)
```

### What steps have you taken to resolve this already?

Tried downgrading to qgrid 1.1.0. Did not resolve.

**Comment by khanhtranchi** [comment]
The similar issue #261

**Comment by ankostis** [comment]
It's a duplicate issue, indeed.

We're going to get more dupes like this, unless some maintainer of this project merge #262 and edits the titles of dupe issues.

With latest jupyter lab, install from PyPi and install JS extensions from `qzchenwl/qgrid` repo (instructions described in #261):
```
pip install qgrid
git clone --depth=1 https://github.com/qzchenwl/qgrid qgrid.git
jupyter labextension install qgrid.git/js/
```

**Comment by tkrabel** [comment]
I have seen that @qzchenwl has created an npm package. However, it's not working on my system. That's why I have created my own npm package.

For those of you who want to install the qgrid JS in the usual way and not from a github repo directly, you can do it now the following way:

    jupyter labextension @8080labs/qgrid

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/tkrabel/qgrid_jupyterlab/master?urlpath=lab/tree/qgrid_demo.ipynb)

You can find a binder demo repo here: [https://github.com/tkrabel/qgrid_jupyterlab](https://github.com/tkrabel/qgrid_jupyterlab)

**Comment by frank-wang-yifei** [comment]
> I have seen that @qzchenwl has created an npm package. However, it's not working on my system. That's why I have created my own npm package.
> 
> For those of you who want to install the qgrid JS in the usual way and not from a github repo directly, you can do it now the following way:
> 
> ```
> jupyter labextension @8080labs/qgrid
> ```
> 
> [![Binder](https://camo.githubusercontent.com/483bae47a175c24dfbfc57390edd8b6982ac5fb3/68747470733a2f2f6d7962696e6465722e6f72672f62616467655f6c6f676f2e737667)](https://mybinder.org/v2/gh/tkrabel/qgrid_jupyterlab/master?urlpath=lab/tree/qgrid_demo.ipynb)
> 
> You can find a binder demo repo here: https://github.com/tkrabel/qgrid_jupyterlab

Thank you very much for providing this solution - got Qgrid to work with my Jupyter Lab after hours of trying.

Just a quick correction - I think you meant to type:

`jupyter labextension install @8080labs/qgrid`

**Comment by gerrymanoim** [comment]
Fixed in https://github.com/quantopian/qgrid/pull/275

**Comment by tkrabel** [comment]
@frank-wang-yifei thanks, I edited my comment from above :)
