### ISSUE TITLE
Jupyterlab 1.1.4 Loading widget...

### ISSUE THREAD

**Issue by ghuname** [quantopian/qgrid#282]
### Environment

* Operating System: Windows 10 64 Bit
* Python Version: `$ python --version` Python 3.7.4
* How did you install Qgrid: (`pip`, `conda`, or `other (please explain)`) conda
* Python packages: `$ pip freeze` or `$ conda list` (please include qgrid, notebook, and jupyterlab versions) 
qgrid '1.1.1'
jupyter lab --version 1.1.4
jupyter --version
jupyter core     : 4.6.1
jupyter-notebook : 6.0.2
qtconsole        : not installed
ipython          : 7.8.0
ipykernel        : 5.1.3
jupyter client   : 5.3.4
jupyter lab      : 1.1.4
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 4.4.0
traitlets        : 4.3.3
* Jupyter lab packages (if applicable): `$ jupyter labextension list`

(base) C:\Users\zoran>jupyter labextension list
JupyterLab v1.1.4
Known labextensions:
   app dir: C:\Users\user\Miniconda3\share\jupyter\lab
        @aquirdturtle/collapsible_headings v0.5.0 enabled  ok
        @jupyter-widgets/jupyterlab-manager v1.0.3 enabled  ok
        @jupyterlab/toc v1.0.1 enabled  ok
        jupyterlab-drawio v0.6.0 enabled  ok
        jupyterlab_templates v0.2.0 enabled  ok
        qgrid v1.1.1 enabled  ok

### Description of Issue

Widget is not shown.

* What did you expect to happen?

I expect table to show.

* What happened instead?

Just a message Loading widget... 

### Reproduction Steps

1. import qgrid
2. qgrid.show_grid(pd.DataFrame(range(20)))
3.
...

### What steps have you taken to resolve this already?

No resolution yet.

**Comment by ghuname** [comment]
I tried solution from https://github.com/tkrabel/qgrid_jupyterlab but with no success.

**Comment by azure31** [comment]
Instead of `pd.DataFrame(range(20))` does `qgrid.show_grid(pd.DataFrame(list(range(20))))` work for you?

**Comment by ghuname** [comment]
Looks like solution above has helped after I restarted everything.

**Comment by ankostis** [comment]
Dupe of #261 (&#264)?

Also instructions in 261 help.

**Comment by ghuname** [comment]
I don't know whether you are talking about https://github.com/tkrabel/qgrid_jupyterlab or somethin else.

**Comment by ankostis** [comment]
Yes, that is why the widget does not load - it stopped being compatible with `jupyterlab-1.0.0+`.
That is what the instructions in #261 is about, and what [`tkrabel/qgrid_jupyterlab` repo](https://github.com/tkrabel/qgrid_jupyterlab) fixes.
