### ISSUE TITLE
jupyterlab 2.0.0 - Error displaying widget: model not found

### ISSUE THREAD

**Issue by ghuname** [quantopian/qgrid#299]
### Environment

* Operating System: Windows 10 64bit
* Python Version: Python 3.7.4
* How did you install Qgrid: pip
* Python packages: 
pip:
ipython-genutils==0.2.0
ipython==7.8.0
jupyter-client==5.3.4
jupyter-core==4.6.1
jupyterlab-server==1.0.7
jupyterlab==2.0.0
notebook==6.0.3
qgrid==1.3.0

conda:

ipython                   7.8.0            py37h39e3cac_0    anaconda
ipython_genutils          0.2.0                    py37_0    anaconda
jupyter_client            5.3.4                    py37_0    conda-forge
jupyter_core              4.6.1                    py37_0    conda-forge
jupyterlab                2.0.0                      py_1    conda-forge
jupyterlab_server         1.0.7                      py_0    conda-forge
notebook                  6.0.3                    py37_0    conda-forge
qgrid                     1.3.0                    pypi_0    pypi

jupyter labextension list:

JupyterLab v2.0.0
Known labextensions:
   app dir: C:\Users\User\Miniconda3\share\jupyter\lab
        @jupyter-widgets/jupyterlab-manager v2.0.0 enabled  ok
        @jupyterlab/toc v3.0.0 enabled  ok
        jupyterlab-plotly v1.5.3 enabled  ok
        plotlywidget v1.5.3 enabled  ok
        qgrid2 v1.1.2 enabled  ok

Uninstalled core extensions:
    qgrid2

### Description of Issue

Running:

import pandas as pd
import qgrid
df = pd.DataFrame({"a": [1, 2, 3, 4], "b": [5, 6, 7, 8]})
grid = qgrid.show_grid(df)
grid

produce an error: Error displaying widget: model not found

In browser console there are many errors:

![image](https://user-images.githubusercontent.com/15207713/76319459-8a8dcf80-62df-11ea-9a9f-edf902528d4a.png)

**Comment by gerrymanoim** [comment]
Hi ghuname - thanks for reporting this. The only thing that obviously stands out to me is the no provider for `jupyter.extensions.jupyterWidgetRegistry`. Can you try some of the steps in https://github.com/quantopian/qgrid/issues/261?

**Comment by ghuname** [comment]
Hi garrymanoim, as the #261 is quite long and people have tried many things, can you please specify what you would like me to do exactly?

**Comment by graidl** [comment]
I experience the same problem under Ubuntu and jupyterlab 2.01, all relevant packages are recent, pip qgrid 1.3.0 and and qgrid2 1.1.2 js part installed either in the official way or directly from the checked out git repo. Tried to follow the hints in #261, no success however. How may I possibly help?

**Comment by ghuname** [comment]
@gerrymanoim, can you please help us a bit?

**Comment by yuezhihan** [comment]
Same problem under jupyterlab 2.0. I reinstalled ipywidgets and jupyterlab many times. The error becomes "Loading widget..." forever.

**Comment by stefaneidelloth** [comment]
Related: https://github.com/quantopian/qgrid/issues/350
