### ISSUE TITLE
Installation instructions not working on Win7

### ISSUE THREAD

**Issue by jonnojohnson** [quantopian/qgrid#3]
I have GitHub for windows installed but the pip install instructions in the demo notebook didn't work for me (cannot find command 'git'). Could you help? Looks like a very cool project.

**Comment by wikiped** [comment]
>We'll likely register the qgrid package on pypi at some point, so pip install can be used without needing git.

It looks like there is still no qgrid package on pypi and the only way to install qgrid on windows is after git installation... Maybe it's worth to mention it in readme.md.

**Comment by ssanderson** [comment]
@wikiped qgrid is on PyPI: https://pypi.python.org/pypi/qgrid.  `pip install qgrid` should Just Work :tm: if you have numpy installed.

**Comment by wikiped** [comment]
Thanks, it did work indeed.
For some reason when I was doing `pip search qgrid` before installing it the only result I was getting is `js.jqgrid`.
