### ISSUE TITLE
More flexible handling of Remote JS

### ISSUE THREAD

**Issue by blink1073** [quantopian/qgrid#32]
What if we used:
https://cdn.rawgit.com/quantopian/qgrid/master/qgrid/qgridjs/

And then substituted "master" for the current git hash as part of a release script?  I can provide a PR with a Makefile that handles releases based on this one: https://github.com/blink1073/oct2py/blob/master/Makefile#L30

**Comment by blink1073** [comment]
Actually, it would be more obvious if the version tag were used:

https://cdn.rawgit.com/quantopian/qgrid/v0.2.0/qgrid/qgridjs/qgrid.js

**Comment by TimShawver** [comment]
You're talking about fixing the fact that this URL:
```
REMOTE_URL = ("https://cdn.rawgit.com/quantopian/qgrid/"
              "ddf33c0efb813cd574f3838f6cf1fd584b733621/qgrid/qgridjs/")
```
is pointing to an old commit, right? That sounds like a good change...loading the old javascript is no good.

**Comment by blink1073** [comment]
Yes, that is what I meant.

**Comment by TimShawver** [comment]
This was fixed a while ago, closing.

**Comment by TimShawver** [comment]
We have to use a specific revision in the CDN URL because rawgit caches javascript permanently.  I switched back to doing that here:
https://github.com/quantopian/qgrid/commit/a019e9a6734059228a39fbe2e71c411e541c406e#diff-2559840b81815e696a22fbaee6294b66L35

It would be nice to automate this though so I'll leave this issue open.

**Comment by TimShawver** [comment]
This is no longer relevant because static exporting is now handled by ipywidgets (since qgrid is now following the conventions for new widgets) which means there's no need for a `REMOTE_URL` anymore.
