### ISSUE TITLE
Support for Python 3.4

### ISSUE THREAD

**Issue by ilovepandas** [quantopian/qgrid#46]
Are there any plan to support 3.4/5?

**Comment by ianozsvald** [comment]
I have been using qgrid (from 6 months back) in a Python 3.4 Notebook environment without problem (though I'll note that now I've upgraded to today's HEAD, I can't get it to render anything with Python 3.4)

**Comment by ianozsvald** [comment]
Just to confirm - I uninstalled and reinstalled ```qgrid``` (see #48) inside an Anaconda Python 3.4 environment (having updated all my usual libs including ```numpy```, `ipython` etc). `qgrid` works fine in my IPython Notebook 4.0.6. Just for reference:
```
Python 3.4.3 |Anaconda 2.3.0 (64-bit)| (default, Oct 19 2015, 21:52:17) 
Type "copyright", "credits" or "license" for more information.

IPython 4.0.1 -- An enhanced Interactive Python.
```

**Comment by ilovepandas** [comment]
Thanks @ianozsvald.  Editing setup.py as suggested in #48 resolves issue.
