### ISSUE TITLE
Possible install issue with an existing Anaconda environment

### ISSUE THREAD

**Issue by ianozsvald** [quantopian/qgrid#48]
Hello, this is a partial bug message, I figured it was worth filing in case others have a similar issue. I have an existing Python 3.4 Anaconda environment called "scratch" (I use it for all side projects). It has numpy, pandas, IPython Notebook and lots more.

I already had a version of qgrid from at least 6 months back, installed back in the mists of time.

I just tried ```pip install -U git+https://github.com/quantopian/qgrid``` (adding ```-U``` to your install notes) and it had a crack at uninstalling my Anaconda-provided numpy+pandas+notebook. I killed it and thankfully it hadn't nuked my environment.

I cloned your repo locally and edited ```setup.py``` to remove the ```install_requires``` dependencies, then ran ```python setup.py install``` and I have the latest version. I'm not sure what happened but I figure it is worth noting (but feel free to close/delete if this isn't a helpful-enough bug report!).

**Comment by twiecki** [comment]
Thanks @ianozsvald. I agree, setting `install_requires` with pegged versions is very aggressive towards the existing environment.

**Comment by ianozsvald** [comment]
In addition (I just tried it again), due either to the Anaconda env or maybe because I have IPython 4.0.1 if I try to use the `setup.py`'s original `install_requires` it (now) reports
```pkg_resources.UnknownExtra: ipython 4.0.1 has no such extra feature 'notebook'```
so I'll continue to experiment having commented out `install_requires`

**Comment by ssanderson** [comment]
We're not actually using requirements.txt for our `setup.py`: https://github.com/quantopian/qgrid/blob/master/setup.py.  

Does Anaconda ignore setup.py and just look at the requirements?

**Comment by ianozsvald** [comment]
@ssanderson Anaconda in this case didn't know anything about `setup.py` - I just ran `python setup.py install` at the command line inside my Anaconda environment. That environment wasn't super-up-to-date (maybe 6 months since I last updated the libraries) and all I remember is that IPython, numpy and more were uninstalled and then pip-installed (which breaks the conda package management, as these were installed through conda). 
I *think* the lack of version pinning in your `setup.py` was the culprit (it saw that the latest versions were needed but older ones were installed, so it nuked my older ones). I'd suggest at least putting pinned version numbers against your install in `setup.py`.
There's a separate process to make a package installable inside the `conda` ecosystem (if that's what you're interested in):
http://conda.pydata.org/docs/build_tutorials/pkgs.html
http://conda.pydata.org/docs/build_tutorials/pkgs2.html

**Comment by TimShawver** [comment]
We've updated setup.py to read from requirements.txt, which has pinned version numbers now.  Sounds like the lack of pinned version numbers is our best theory as to why this happened so I'm going close this now.
