### ISSUE TITLE
Incorrect filter range on column with 2 numeric values

### ISSUE THREAD

**Issue by fonnesbeck** [quantopian/qgrid#5]
When trying to use the filter on a column consisting of zeros and ones, filter shows a range of `1 - 1` rather than `0 - 1`.

![screen capture](http://d.pr/i/1iZno+)

Running current master with IPython 2.2 on OS X 10.10 in Safari.

**Comment by TimShawver** [comment]
This is fixed in the qgrid 1.0 beta.  See the installation instructions on the [updated readme page](https://github.com/quantopian/qgrid#installation) to try it out.
