### ISSUE TITLE
Qgrid are not displayed on jupyterhub when using runipy to run ipynb file

### ISSUE THREAD

**Issue by akshaykandul** [quantopian/qgrid#52]
I am using runipy to run a ipython notebook and save the notebook output as a new notebook. Qgrid is working properly when running notebook on jupyterhub, but doesn't work when using runipy. Code is executed properly, only qgrid is not displayed instead it displays following

>var path_dictionary = { jquery_drag: "https://cdn.rawgit.com/quantopian/qgrid/72d356cb123fab413dba73ec46616e4916fbd827/qgrid/qgridjs//lib/jquery.event.drag-2.2", slick_core: "https://cdn.rawgit.com/quantopian/qgrid/72d356cb123fab413dba73ec46616e4916fbd827/qgrid/qgridjs//lib/slick.core.2.2", slick_data_view: "https://cdn.rawgit.com/quantopian/qgrid/72d356cb123fab413dba73ec46616e4916fbd827/qgrid/qgridjs//lib/slick.dataview.2.2", slick_check_box_column: "https://cdn.rawgit.com/quantopian/qgrid/72d356cb123fab413dba73ec46616e4916fbd827/qgrid/qgridjs//lib/slick.checkboxselectcolumn", slick_row_selection_model: "https://cdn.rawgit.com/quantopian/qgrid/72d356cb123fab413dba73ec46616e4916fbd827/qgrid/qgridjs//lib/slick.rowselectionmodel", slick_grid: "https://cdn.rawgit.com/quantopian/qgrid/72d356cb123fab413dba73ec46616e4916fbd827/qgrid/qgridjs//lib/slick.grid.2.2", data_grid: "https://cdn.rawgit.com/quantopian/qgrid/72d356cb123fab413dba73ec46616e4916fbd827/qgrid/qgridjs//qgrid", date_filter: "https://cdn.rawgit.com/quantopian/qgrid/72d356cb123fab413dba73ec46616e4916fbd827/qgrid/qgridjs//qgrid.datefilter", slider_filter: "https://cdn.rawgit.com/quantopian/qgrid/72d356cb123fab413dba73ec46616e4916fbd827/qgrid/qgridjs//qgrid.sliderfilter", text_filter: "https://cdn.rawgit.com/quantopian/qgrid/72d356cb123fab413dba73ec46616e4916fbd827/qgrid/qgridjs//qgrid.textfilter", filter_base: "https://cdn.rawgit.com/quantopian/qgrid/72d356cb123fab413dba73ec46616e4916fbd827/qgrid/qgridjs//qgrid.filterbase", handlebars: "https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/2.0.0/handlebars.min" }; var existing_config = require.s.contexts._.config; if (!existing_config.paths['underscore']){ path_dictionary['underscore'] = "https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.7.0/underscore-min"; } if (!existing_config.paths['moment']){ path_dictionary['moment'] = "https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.3/moment.min"; } if (!existing_config.paths['jqueryui']){ path_dictionary['jqueryui'] = "https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/jquery-ui.min"; } require.config({ paths: path_dictionary }); if (typeof jQuery === 'function') { define('jquery', function() { return jQuery; }); } require([ 'jquery', 'jquery_drag', 'slick_core', 'slick_data_view' ], function(){('#b97d5b3e-85fe-4920-8635-2e5ddd467eff').closest('.rendered_html').removeClass('rendered_html'); require([ 'slick_check_box_column', 'slick_row_selection_model', 'slick_grid' ], function(){ require(["data_grid"], function(dgrid){ var grid = new dgrid.QGrid('#b97d5b3e-85fe-4920-8635-2e5ddd467eff',

**Comment by jakirkham** [comment]
This has been opened as an issue on `runipy` ( https://github.com/paulgb/runipy/issues/106 ). I think this is an issue with `runipy`. That being said, it would be nice if one could dump an HTML file from qgrid. Is that possible?

**Comment by TimShawver** [comment]
I've never tried qgrid with runipy so I wouldn't expect it to work.
