### ISSUE TITLE
Export to an HTML file

### ISSUE THREAD

**Issue by jakirkham** [quantopian/qgrid#53]
It might be nice to be able to spit out a separate HTML file that works independently of the notebook. This would allow one to share the HTML file easily without requiring iPython/Jupyter.

**Comment by TimShawver** [comment]
Yea this would be a nice feature. We have a `remote_js` flag on the show_grid function which would allow you to render qgrid such that it could be rendered by nbviewer.  That's how the [demo notebook] (http://nbviewer.jupyter.org/gist/TimShawver/b4bc80d1128407c56c9a) on nbviewer works.  Let me know if you need help with that, the way to use it is not documented too well.

From my experience working on that remote_js flag I don't think supporting exporting to HTML is something we want to do.  The reason is it's a feature that would be tightly coupled with the way jupyter notebook's export to html feature works, so it's something that will break easily.  The only reason I was willing to add the nbviewer support is because the demo notebook helps to attract people to the project.

**Comment by TimShawver** [comment]
This appears to be almost functional already.  Here are the steps:

1. After importing qgrid and running `nbinstall` at the top of your notebook, add the following line to set some options:
```
qgrid.set_defaults(remote_js=True, show_toolbar=True)
```
2. Render a qgrid and notice the Export button above it.  
3. Click Export to generate a version of the grid that can be rendered outside of the jupyter notebook.  You'll actually see two grids there at this point, and that's OK.
4. Click save to save your notebook.
5. Go to File, Download As, Html to download your notebook as a standalone HTML file.

The only thing that didn't work for me is the filter icons in the column headers of the grid were missing in the resulting HTML file.  The grid appeared to be totally functional other than that.

**Comment by johnjoo1** [comment]
I would really like to use qgrid outside of Jupyter notebooks to save dataframes as interactive html tables. 

It would be great if you had to first create a qgrid object which has methods show_grid and export. 

Currently, it looks like we'd have to create another method that is very similar to save_grid just to have the grid object accessible for the grid.export() call.

**Comment by valentas-kurauskas** [comment]
I tried above steps in the hope to get this working for reveal slides (`jupyter nbconvert presentation.ipynb --to slides --post serve`). Unfortunately, it does not give a useful output yet: once I add more than one four columns, the table becomes garbled (in the slides, not in the notebook) with all columns of extremely small width. Also the filter icon image is broken in the slides.

**Comment by motin** [comment]
Please re-open this issue until a method that works with latest qgrid works :)

`qgrid.set_defaults(remote_js=True, show_toolbar=True)` yields `TypeError: set_defaults() got an unexpected keyword argument 'remote_js'`.

I tried exporting using embed_minimal_html:

```
import pandas as pd
import qgrid
from ipywidgets.embed import embed_minimal_html
from IPython.display import IFrame

df = pd.read_csv(
  "https://gist.githubusercontent.com/rgbkrk/a7984a8788a73e2afb8fd4b89c8ec6de/raw/db8d1db9f878ed448c3cac3eb3c9c0dc5e80891e/2015.csv"
)
view = qgrid.show_grid(df)
embed_minimal_html('qgrid.html', views=[view], title='QGrid')
```
While this results in a standalone web-page (can be displayed with `IFrame("qgrid.html", width=1000, height=400)`), its interactivity is broken. It tries to include non-existing `qgrid.js` and `base/js/dialog.js` relative to the current directory.

**Comment by motin** [comment]
Aha, just read https://github.com/quantopian/qgrid/issues/110#issuecomment-336929573 - worth including here as well:

> The export button is gone in qgrid 1.0 and it's no longer possible to export a fully functional version of qgrid to static html, because in the new version of qgrid the sorting/filtering logic is done on the server. That being said, you should still be able to export a partially functional version of qgrid where sorting/filtering is broken (and only 200 rows are included) once jupyter-widgets/ipywidgets#1597 is fixed.
> 
> I realize that's probably not all that useful to people so another alternative that might be a better option is to use the new "binder" service for rendering live notebooks. I'm using it to host the demo notebook for qgrid and it's been great so far: https://beta.mybinder.org/v2/gh/quantopian/qgrid-notebooks/master?filepath=index.ipynb
> 
> I'm going to close this since I no longer plan to provide full support for static html exporting, and I think "binder" will be a suitable alternative for a lot of users.

**Comment by naomatheus** [comment]
Hi @motin 
I am running a jupyter notebook and hosting it via binder.
Do you experience your server connection dropping frequently? If so how did you manage this?

Did you have any issues rendering your QgridWidget. If so do you have a suggestion for how you solved this?

**Comment by naomatheus** [comment]
will open this issue elsewhere
