### ISSUE TITLE
Objects don't display properly

### ISSUE THREAD

**Issue by maxim-lian** [quantopian/qgrid#57]
Objects, including `PeriodIndex`s don't display properly. And some objects raise because they're not JSON serializable.

Calling `str` on these first would solve this

`pd.DataFrame({'a': pd.Series(5, index=pd.period_range(start='2000', periods=10, freq='B'))}).pipe(qgrid.show_grid)`

![image](https://cloud.githubusercontent.com/assets/5635139/12810769/336589d0-caf6-11e5-91d2-67c0e78e03a7.png)

**Comment by TimShawver** [comment]
Thanks, this would be a nice one to fix.
