### ISSUE TITLE
Adding and Removing Rows does not work

### ISSUE THREAD

**Issue by mirage007** [quantopian/qgrid#59]
The following code seems to throw some javascript errors when I click on Add/Remove Rows:
Selection and Editing still seem to work fine.

This is using python 2.7, IPython 4.1.1 and master branch of qgrid.

```
import qgrid
import IPython
print IPython.__version__

import pandas
import numpy as np

res = pandas.DataFrame(np.arange(20).reshape(10,2))
res.index = np.arange(len(res))

qgrid.nbinstall(overwrite=True)
qgrid.show_grid(res, show_toolbar=True)

```

The exception I see in the chrome js console reads:

Exception in Comm callback Each data element must implement a unique 'id' property undefined Object {parent_header: Object, msg_type: "comm_msg", msg_id: "b14613d9-f5a9-4c99-bc7e-3d8516296885", content: Object, header: Object…}buffers: Array[0]channel: "iopub"content: Objectcomm_id: "83a82de5e21e4a588d83b7d054924db6"data: Objectcontent: Objectmethod: "custom"__proto__: Object__proto__: Objectheader: Objectmetadata: Object__proto__: Objectmsg_id: "b14613d9-f5a9-4c99-bc7e-3d8516296885"msg_type: "comm_msg"parent_header: Object__proto__: Object

Any thoughts?

**Comment by rdhyee** [comment]
As I've been getting up to speed with qgrid, I've been fixing problems on my fork...take a look at https://github.com/quantopian/qgrid/compare/master...rdhyee:fix-add-row.  I'm not ready to issue a PR yet.   https://github.com/quantopian/qgrid/pull/58 might also be relevant.

**Comment by mirage007** [comment]
I am able to work around this issue for now by simply adding a few ipywidgets buttons that update grid.df with a new dataframe. This probably does not scale very well but works for now as long as the table is small.

**Comment by blink1073** [comment]
I can reproduce, I will fix this in #58.

**Comment by blink1073** [comment]
This should be fixed now in #58, @TimShawver, can you verify?

**Comment by TimShawver** [comment]
Cool, I'll take a look today.

**Comment by TimShawver** [comment]
This is fixed by https://github.com/quantopian/qgrid/pull/65
