### ISSUE TITLE
qgrid does not appear

### ISSUE THREAD

**Issue by jmerkow** [quantopian/qgrid#66]
I am trying to load a qgrid from a pandas dataframe, but when I run:

    import qgrid
    import pandas as pd
    df=pd.DataFrame([dict(idx=0,A=1),dict(idx=2,A=2)])`

Nothing happens (no error or anything else).  Here are errors listed in my JS console:

> Couldn't create a view for model id 'd7522ce5e25148848c5e49c7fdf8f795'  --  TypeError: require is not a function(…)
> (anonymous function) @ utils.js:760
> z @ VM218:22R @ VM218:22
> (anonymous function) @ VM218:22
> g @ VM218:22
> 
> utils.js:760 Could not create view  --  WrappedError {stack: "Error: Couldn't create a view for model id 'd7522c…39d168d24e1b201697c328:1:0), <anonymous>:22:8069)", message: "Couldn't create a view for model id 'd7522ce5e25148848c5e49c7fdf8f795'", error_stack: Array[3]}(anonymous function) @ utils.js:760
> z @ VM218:22
> R @ VM218:22
> C @ VM218:22T @ VM218:22
> g @ VM218:22
> 
> utils.js:760 Could not display model  --  WrappedError {stack: "Error: Could not create view↵    at new Error (nat…39d168d24e1b201697c328:1:0), <anonymous>:22:8069)", message: "Could not create view", error_stack: Array[4]}(anonymous function) @ utils.js:760
> z @ VM218:22
> R @ VM218:22
> C @ VM218:22T @ VM218:22
> g @ VM218:22

**Comment by TimShawver** [comment]
I don't know what those errors mean, but I would suggest looking at the [sample notebook on nbviewer](https://github.com/quantopian/qgrid/blob/master/qgrid_demo.ipynb) to see how qgrid is used.  Two things that I see missing:

1. You need to run nb_install to install the widget to your local jupyter notebook instance
2. You need to call show_grid to actually render the DataFrame.  Qgrid doesn't automatically take over DataFrame rendering, it has to be told explicitly via a call to show_grid.

To get the sample notebook running locally, clone the repository using 
`
git clone https://github.com/quantopian/qgrid.git
`
 and then follow the steps in the section [Running the Demo Locally] (https://github.com/quantopian/qgrid#running-the-demo-locally).  Apologies if the docs are confusing, I'm going to try to clean them up a bit.

**Comment by jmerkow** [comment]
Ooops I think I copied the wrong python code.  How silly of me.  This is the code I am using:

```
import qgrid

qgrid.nbinstall(overwrite=True)  # copies javascript dependencies to your /nbextensions folder
qgrid.set_defaults(remote_js=True)
import pandas as pd
import numpy as np
randn = np.random.randn

# Set this pandas option to prevent the grid from being too big
pd.set_option('display.max_rows', 8)

# Get a pandas DataFrame containing the daily prices for the S&P 500 from 1/1/2011 - 1/1/2014
from pandas.io.data import get_data_yahoo
spy = get_data_yahoo(
    symbols='SPY',  
    start=pd.Timestamp('2011-01-01'),  
    end=pd.Timestamp('2014-01-01'),
    adjust_price=True,
)
qgrid.show_grid(spy)
```

**Comment by jmerkow** [comment]
Where specifically is nbinstall supposed to copy the extension to?

**Comment by djchou** [comment]
Your code worked for me.  What version of qgrid / pandas are you using?

**Comment by jmerkow** [comment]
So, I no longer use the machine I had this issue on.  I tried it on my new machine, (also with safari instead of chrome) and worked fine.
If I run into trouble again, I will update, but for now I will close this issue.

**Comment by methodds** [comment]
Unfortunately I have the same issue and used exactly the instructions from the example notebook. Is there a way to debug this? And what information would you need? Browser, packages, etc?

**Comment by keluc** [comment]
I had the same problem when working with anaconda (after conda install qgrid).  Finally I succeeded to get it working in anaconda as follows:
- I moved the folders created by qgrid.nbinstall to the anaconda folder ... \share\jupyter\nbextensions
- I had to conda install ipywidgets
After this the qgrid appeared. I tried to look into the qgrid.nbinstall function, but at first glance it was not clear to me what should be changed.

**Comment by brycepg** [comment]
I had trouble finding the qgrid extension location. It's located in `~/.local` if you did `pip install --user ...`:

Copying the files from @keluc fixed it for me:

     cp -r ~/.local/share/jupyter/nbextensions/qgridjs/ ~/anaconda3/share/jupyter/nbextensions/

Thanks!

**Comment by TimShawver** [comment]
In case anyone is still seeing this issue, please try installing the new qgrid 1.0 beta using the instructions here: https://github.com/quantopian/qgrid#installation.  As you'll see in those instructions, the `nbinstall` step that appears to be an issue for some people is no longer required.  This is because qgrid 1.0 follows the recommended installation/deployment guidelines provided by the ipywidgets team.

**Comment by 4bic** [comment]
I have qgrid installed via `conda install qgrid` but in the notebook, I get no response;
`import qgrid`
`qgrid.show_grid(df)`
are there other steps that I need to take beyond importing it?

**Comment by sshixu** [comment]
Upgrading to the latest browser may solve the issue.

**Comment by markfink** [comment]
I tried to get it going on a simple sample but no luck so far...
![image](https://user-images.githubusercontent.com/33456/39398085-f38bcce4-4b08-11e8-8a08-ca07812c5a55.png)

I used pip for installation on python3. qgrid==1.0.2
chrome: Version 62.0.3202.94 (Official Build) (64-bit)
running on uptodate arch linux... (hope qgrid is not Windows only)

**Comment by manik-agg** [comment]
@markfink : Hey i am having the same problem with exaclty the same code but I am using Windows version. Were you able to rectify the same.

**Comment by emgong** [comment]
Same problem here

**Comment by brettbrocato** [comment]
All, I have had some challenges on WinPy 3.6.7 / newer Chome / Notebook / fresh install of qgrid and samples today, but it seems functional.  Two suggestions:

1. My dfs only show up after qgrid_widget.get_changed_df(), not before.
2. See if your notebook says "Untrusted" on the top right or if you have any messages like the one below in your cli:

[W 09:03:28.306 LabApp] Notebook winpyfolder/folder/mynotebook.ipynb is not trusted

If you do **and only if you trust the notebook author,** click trust on the top right of the notebook.  Specifically you may need to click untrusted and then trust.

**Comment by jkmgeo** [comment]
@brettbrocato to see the df's, be sure you're saving the widget to a variable, and then calling that variable so it's shown in the output cell; this got my for the longest time.

```
import qgrid
qgrid_widget = qgrid.show_grid(df)
qgrid_widget # omitting this line saves the widget to a variable but it won't show
```

Apologies if you already knew this - just thought I'd place this here for anyone new to qgrid who stumbles across this!

**Comment by coltmac** [comment]
I'm am experiencing the same problem as the OP:  web app works in jupyter notebooks (local), it works in Voila (local), but when I run it with Heroku - it doesn't display the jupyter notebook displays.

Heroku Warning:
```
2019-07-01T01:29:41.993853+00:00 heroku[router]: at=info method=GET path="/voila/bqplot.js" host=damp-retreat-67638.herokuapp.com request_id=e2e9446d-372c-41bb-b22f-90c4ae0e27b3 fwd="24.8.52.201" dyno=web.1 connect=0ms service=3ms status=404 bytes=240 protocol=https
2019-07-01T01:29:41.996535+00:00 app[web.1]: WARNING:tornado.access:404 GET /voila/bqplot.js (10.67.241.187) 1.09ms
2019-07-01T01:29:42.002571+00:00 app[web.1]: WARNING:tornado.access:404 GET /voila/qgrid.js (10.63.252.246) 0.90ms
2019-07-01T01:29:42.001537+00:00 heroku[router]: at=info method=GET path="/voila/qgrid.js" host=damp-retreat-67638.herokuapp.com request_id=6d6fdbe9-706d-4fdc-bb82-88c3462870c3 fwd="24.8.52.201" dyno=web.1 connect=1ms service=2ms status=404 bytes=240 protocol=https
```

it seems to be having trouble with "GET /voila/qgrid.js" and "GET /voila/bqplot.js"

Could this be a related issue?
