### ISSUE TITLE
Jupyter kernel crashes

### ISSUE THREAD

**Issue by ericgcoker** [quantopian/qgrid#70]
I am using Python 2.7.8 and Jupyter 4.0.6 on CENTOS 6. I use the following code to render qgrid.
"import qgrid
qgrid.show_grid(df)"

In some cases it works with no issue.  Although with wider df's I get a "kernel restarting" error on Jupyter which states "The kernel appears to have died. It will restart automatically". This is the only time I've had this occur on Jupyter (when I use qgrid).
I was able to fix this by changing my PANDAS dataframe column types FROM 'category'. It seems qgrid crashes when trying to render PANDAS 'category' data types?

Further, with PANDAS datetime column types, it does not display the 'time' part of the field.

**Comment by TimShawver** [comment]
Both of these issues (displaying category and datetime columns) should be fixed in the new qgrid 1.0 beta.  See the installation instructions on the [updated readme page](https://github.com/quantopian/qgrid#installation).

I'm going to go ahead and close this since it's old.
