### ISSUE TITLE
update version on pypi

### ISSUE THREAD

**Issue by jdavidheiser** [quantopian/qgrid#74]
The version currently available on pypi force-downgrades several packages.  It would be nice to update to the current version on pypi, which has fixed requirements.txt, so this doesn't happen anymore.

**Comment by TimShawver** [comment]
Sorry about this. I'll update the release on pypi next week (need help from a coworker because I don't have access). In the meantime you should just install from github instead with `pip install git+https://github.com/quantopian/qgrid`

**Comment by TimShawver** [comment]
This is fixed in release 0.3.2, which is now available on pypi.
