### ISSUE TITLE
qgrid requires ipywidgets-4.1.1

### ISSUE THREAD

**Issue by jdavidheiser** [quantopian/qgrid#75]
I'm putting this here both as an issue for potential fixing, and a warning to others who might burn a whole day trying to debug this.  qgrid will _not_ work with version 5+ of ipywidgets.  There has been significant code refactoring, and the relevant javascript that's used by qgrid is no longer where expected.  I've spent a little time looking into what it would take to update qgrid to work with ipywidgets 5+, but am not familiar enough with the codebases to have a good feel for how difficult the task will be.

**Comment by TimShawver** [comment]
Sorry about this! I've updated requirements.txt and the README to reflect this limitation for now.  Hopefully I can get around to working on it soon.

**Comment by TimShawver** [comment]
@jdavidheiser I just merged a fix for this.  You'll need to install from github with `pip install git+https://github.com/quantopian/qgrid` to get the latest from master to get the fix.  I'll update pypi in the next couple of days once I have some other people test it out.  If you get a chance to test it, let me know if it works for you.  Thanks.

**Comment by TimShawver** [comment]
This is fixed in release 0.3.2, which is now available on pypi.
