### ISSUE TITLE
Get error: 'No such comm target registered: jupyter.widget.version'

### ISSUE THREAD

**Issue by tomVeloso** [quantopian/qgrid#76]
I have the following:

jupyter==1.0.0
jupyter-client==4.2.2
jupyter-console==4.1.1
jupyter-core==4.1.0
ipywidgets==4.1.1
widgetsnbextension==1.2.3

When I try to run the 5 cell in the demo notebook I got
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.version

**Comment by TimShawver** [comment]
Which version of Jupyter notebook do you have installed? I just tested the various versions of the notebook and ran into this issue with the 4.2.x version, but the versions below that worked fine.  I've updated the README and requirements.txt to reflect this limitation.  Sorry about this, hopefully I can get to fixing it soon.

**Comment by tomVeloso** [comment]
Great!

**Comment by post2web** [comment]
Can someone share how to downgrade jupyter?
