### ISSUE TITLE
Add support for SlickGrid maintained fork

### ISSUE THREAD

**Issue by gallamine** [quantopian/qgrid#91]
SlickGrid is no longer maintained (as of 2 years ago). The maintained fork is now at https://github.com/6pac/SlickGrid
This repo has being actively maintained. 
Moving qgrid to the active fork should be considered.

**Comment by TimShawver** [comment]
Thanks for this suggestion.  This is fixed because I'm now using my own fork of the 6pac fork in the new qgrid 1.0 beta.  That fork is here: https://github.com/quantopian/SlickGrid in case you're curious.

**Comment by itegebo** [comment]
It would be helpful to know why there's a quantopian fork of 6pac's.
