### ISSUE TITLE
Feature request: display checkboxes for boolean columns

### ISSUE THREAD

**Issue by andyfaff** [quantopian/qgrid#95]
qgrid is awesome for displaying DataFrames which can be edited. However, it doesn't seem to be possible to edit columns of DataFrames that contain `bool`. They get displayed as `true` and `false`, but one can't change the contents.
It would be great as a first step if the boolean values could be edited and the icing on the cake would be if they could be edited like a checkbox.

**Comment by lucienp** [comment]
+1

But for a temporary workaround, cast the dataframe column to a str to get the checkbox filters

**Comment by andyfaff** [comment]
So if I cast to str then are the rows displayed as checkboxes?

On 23 Oct 2016 2:02 pm, "lu" <notifications@github.com> wrote:
>
> +1
>
> But for a temporary workaround, cast the dataframe column to a str to get
the checkbox filters

**Comment by lucienp** [comment]
Works for me on 0.3.1. Im doing something like this which casts the whole dataframe:

`df= df.astype(str)`

Depending on what your data looks like though, you may want to select a specific column.

**Comment by TimShawver** [comment]
I've added support for boolean columns (displayed as checkboxes, per your suggestion) in qgrid 1.0, which is currently available in beta form.  See the installation instructions on the [updated readme page](https://github.com/quantopian/qgrid#installation).

Thanks for the suggestion 🥇
